### ISSUE TITLE
Obiecująco, ale...

### ISSUE THREAD

**Issue by cinkonaap** [agaSemrau/education#1]
Dzieńdobry,

pani Agnieszko, jestem osobą odpowiedzialną za przejrzenie pani rozwiązania.

Wszystko wygląda obiecująco, niestety struktura repozytorium jest błędna, co uniemożliwiło nam (bez "dużego" wysiłku) lokalne uruchomienie pani rozwiązania.

Oczywiście udało nam się po chwili zabawy to uruchomić, i efekt jest zadawalający.

Proponowałbym więc przyjrzeć się następującym problemom, poprawić je, i odbić mi wątek:
- Czy `dist/` i `/zadanie` powinny być oddzielnie? Z którego miejsca więc uruchomić web serwer? (sym-link) nie są tutaj dobrym rozwiązaniem
- Brak package.json, przez co nie mogliśmy łatwo wykonać `gulp`
- Nie wrzucone do `dist/` pliki (`css`, `js`) które są ładowane (problem jest powiązanym z tymi powyżej)

**Comment by agaSemrau** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Panie Marcinie,
 
Dziękuję za szybką odpowiedź.
Faktycznie miałam problemy z poprawnym skonfigurowaniem gulpa (dość dawno tego nie robiłam) i może coś poszło nie tak. U mnie lokalnie jest package.json tylko chyba przegapiłam i nie dodałam go do GITa :/
Postaram się zrobić jakieś poprawki w strukturze repo, chociaż przyznaję, że tematy nie są moją najmocniejszą stroną :)
Dam znać mailowo, kiedy tylko wprowadzę zmiany.
 
Pozdrawiam,
Agnieszka Semrau
 
 
Nie wiem dlaczego nie trafił do repo. Problem jest chyba w tym, że Dnia Czwartek, 18 Sierpnia 2016 15:51 Marcin Horoszko notifications@github.com napisał(a)

Dzieńdobry,
pani Agnieszko, jestem osobą odpowiedzialną za przejrzenie pani rozwiązania.
Wszystko wygląda obiecująco, niestety struktura repozytorium jest błędna, co uniemożliwiło nam (bez "dużego" wysiłku) lokalne uruchomienie pani rozwiązania.
Oczywiście udało nam się po chwili zabawy to uruchomić, i efekt jest zadawalający.
Proponowałbym więc przyjrzeć się następującym problemom, poprawić je, i odbić mi wątek:

Czy dist/ i /zadanie powinny być oddzielnie? Z którego miejsca więc uruchomić web serwer? (sym-link) nie są tutaj dobrym rozwiązaniem
Brak package.json, przez co nie mogliśmy łatwo wykonać gulp
Nie wrzucone do dist/ pliki (css, js) które są ładowane (problem jest powiązanym z tymi powyżej)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/agaSemrau/education","title":"agaSemrau/education","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/agaSemrau/education"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Obiecująco, ale... (#1)"}],"action":{"name":"View Issue","url":"https://github.com/agaSemrau/education/issues/1"}}}
// ]]>

**Comment by cinkonaap** [comment]
Pani Agnieszko,

sam gulp/node nie był wymagany w zadaniu, chociaż przyznam że jego użycie jest plusem. Jeśli nie poradzi sobie pani z odpowiednim przygotowaniem repozytorium korzystając z gulpa, proszę chociaż przygotować repozytorium tak, aby bez problemowo można było uruchomić serwer lokalnie (czyli np. umieścić w odpowiednim miejscu skompilowane, gotowe assety).

Mały tip: proszę nie zapomnieć o dodaniu `node_modules` do .gitignore :smile:

**Comment by agaSemrau** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Panie Marcinie,
 
Faktcznie nieźle tam namieszałam. Mam nadzieję, że teraz będzie dobrze... Tutaj założyłam nowe repozytorium:
https://github.com/agaSemrau/zadanie2
 
Pozdrawiam,
Agnieszka Semrau
 
Dnia Piątek, 19 Sierpnia 2016 10:01 Marcin Horoszko notifications@github.com napisał(a)

Pani Agnieszko,
sam gulp/node nie był wymagany w zadaniu, chociaż przyznam że jego użycie jest plusem. Jeśli nie poradzi sobie pani z odpowiednim przygotowaniem repozytorium korzystając z gulpa, proszę chociaż przygotować repozytorium tak, aby bez problemowo można było uruchomić serwer lokalnie (czyli np. umieścić w odpowiednim miejscu skompilowane, gotowe assety).
—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/agaSemrau/education","title":"agaSemrau/education","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/agaSemrau/education"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cinkonaap in #1: Pani Agnieszko,\r\n\r\nsam gulp/node nie był wymagany w zadaniu, chociaż przyznam że jego użycie jest plusem. Jeśli nie poradzi sobie pani z odpowiednim przygotowaniem repozytorium korzystając z gulpa, proszę chociaż przygotować repozytorium tak, aby bez problemowo można było uruchomić serwer lokalnie (czyli np. umieścić w odpowiednim miejscu skompilowane, gotowe 
assety)."}],"action":{"name":"View Issue","url":"https://github.com/agaSemrau/education/issues/1#issuecomment-240954109"}}}
// ]]>
